version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
#    pulls the latest version of the image
    container_name: zookeeper
    ports:
      - '2181:2181'
#      host to container port is being mapped (zookeeper usually uses 2181 port for client connection)
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
#      This line specifies that the kafka service depends on the zookeeper service.
#  Docker Compose will start the Zookeeper container before starting the Kafka container to satisfy this dependency.
